import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/module/Header/Header";
import { GlobalContext } from "@/context/Context";
import { QueryProvider } from "@/query/QueryProvider";
import Footer from "@/module/Footer";
import { GlobalCartContext } from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ashyo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/logo_site1.ico"></link>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalContext>
          <QueryProvider>
            <GlobalCartContext>
              <Header />

              {children}
              <Footer />
            </GlobalCartContext>
          </QueryProvider>
        </GlobalContext>
      </body>
    </html>
  );
}
